name: Deploy to Server

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 67.205.142.130
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/root/.bun/bin
            cd /var/www/${{ github.ref_name == 'main' && 'klypse.io' || 'dev.klypse.io' }}/app
            git pull origin ${{ github.ref_name }}
            make install
            # Kill existing process on port 3000
            lsof -ti:3000 | xargs kill -9 || true
            # Start the server in the background
            cd packages/backend && bun src/server.ts &
            # Wait a bit for the server to start
            sleep 5