name: Deploy to Server

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 67.205.142.130
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/root/.bun/bin
            if [[ "${{ github.ref_name }}" == "main" ]]; then
              cd /var/www/klypse.io/app
              git pull origin main
              make install
              make restart-prod
            else
              cd /var/www/dev.klypse.io/app
              git pull origin dev
              make install
              make restart-dev
            fi